version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c 'cd ./app && python main.py'
    stdin_open: true
    tty: true
volumes:
  db_data: